site_name: The CaRCC Handbook
docs_dir: handbook
nav:
  - About: about.md
  - Handbook: index.md
  - Resources: resources.md
plugins:
  - search
  - bibtex:
      bib_file: "references.bib"
markdown_extensions:
  - footnotes